#!/bin/bash

error(){ 
    echo "ERREUR : parametres invalides !" >&2 
    echo "utilisez l'option -h pour en savoir plus" >&2 
    exit 1 
} 

usage(){ 
    echo "Usage: mkalias [options]" 
    echo "	-h :			Show this help" 
    echo "	-i=<GUI|CLI> :		Open with <GUI|CLI> interface" 
} 


traitement(){ 
	if [[ "$1" = "=CLI" ]]; then
		sudo bash $HOME/aliaz/aliaz.sh -iCLI
	elif [ "$1" = "=GUI" ]; then
		sudo bash $HOME/aliaz/aliaz.sh -iGUI
	else
		error
	fi 
	
} 

[[ $# -lt 1 ]] && error 

while getopts ":i:h" option; do 
    case "$option" in 
        i) traitement "$OPTARG";; 
        :) error ;; # il manque une valeur ($option = 'b' ici) 
        h) usage ;; 
        *) error ;; 
    esac 
done
