#!/bin/bash

## COLORS
cyan='\e[0;36m' 
green='\e[0;34m'
okegreen='\033[1;92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[0;33m'
BlueF='\e[1;34m' 
RESET="\033[00m" 
orange='\e[38;5;166m'
grey='\e[1;90m'
purple='\e[0;35m'

error(){ 
    echo -e "\e[1;31mERROR\033[00m : $1\033[00m" >&2 
    echo -e "Use the \e[0;33m-h \033[00mor \e[0;33m--help\033[00m option to learn more" >&2 
    exit 1 
} 

usage(){ 
    echo "Usage: mkalias [options]" 
    echo ""
    echo "OPTIONS :"
    echo "	--help (-h)	: Show this help" 
    echo "	--gui		: Open with GUI interface" 
    echo "	--cli		: Open with CLI interface" 
    echo ""
    echo "Usage: mkalias -n={name} -c={command} [-C] [-H]"
	echo ""
	echo "OPTIONS (oneline) :"
    echo "	--name (-n)	: Enter the name of your command" 
    echo "	--command (-c)	: Enter command executed" 
    echo "	--clear (-C)	: Clear terminal" 
    echo "	--home (-H)	: Go to home" 
    echo ""
    echo "If the option --clear (-C) or --home (-H) if they are not entered, they are considered false and will not be taken into account when creating the alias."
    echo ""
    
} 

ifNull() {

	if [ "$PARMTS_PARSE" = ';;false;false;false;false;false' ]; then
		error "No parameters entered !"
	fi
	
	if [ "$HELP" = 'false' ]; then
	
		if [ -z "$NAME" ] && [ -z "$COMMAND" ]; then
			error "No value for parameters \e[1;34m--name\033[00m/\e[1;34m-n\033[00m and \e[1;34m--command\033[00m/\e[1;34m-c"
		elif [ -z "$NAME" ]; then
			error "No value for parameter \e[1;34m--name\033[00m/\e[1;34m-n"
		elif [ -z "$COMMAND" ]; then
			error "No value for parameter \e[1;34m--command\033[00m/\e[1;34m-c"
		fi
	fi
	
}


NAME=
COMMAND=
CLEAR=false
mkHOME=false
GUI=false
CLI=false
HELP=false

DIR=
PARMTS_PARSE="$NAME;$COMMAND;$CLEAR;$mkHOME;$GUI;$CLI;$HELP"

for i in "$@"
do
case $i in
    -h|--help)
    HELP=true
    usage
    shift # past argument value
    ;;
    --gui ) 
    GUI=true
    cd $HOME/aliaz/ && ./aliaz.sh --gui 
    shift
    ;;
	--cli ) 
	CLI=true
	cd $HOME/aliaz/ && ./aliaz.sh --cli 
	shift
	;;
	-n=*|--name=*)
	NAME="${i#*=}"
	shift
	shift
	;;
	-c=*|--command=*)
	COMMAND="${i#*=}"
	shift
	shift
	;;
    -C | --clear) 
    CLEAR=true
    shift
    shift
    ;;
    -H | --home) 
    mkHOME=true
    shift
    shift
    ;;
    *)
    error "invalid parameters !"
    shift
    ;;
esac
done

if [ "$GUI" = 'false' ] && [ "$CLI" = 'false' ] && [ "$HELP" = 'false' ]; then
	
	if [ -z "$NAME" ] || [ -z "$COMMAND" ]; then
		ifNull
	else
		if  [ "$mkHOME" = 'true' ] && [ "$CLEAR" = 'false' ]; then
			cd $HOME/aliaz/ && ./aliaz.sh --name="$NAME" --command="$COMMAND" --home
		elif [ "$mkHOME" = 'false' ] && [ "$CLEAR" = 'true' ]; then
			cd $HOME/aliaz/ && ./aliaz.sh --name="$NAME" --command="$COMMAND" --clear
		elif [ "$mkHOME" = 'true' ] && [ "$CLEAR" = 'true' ]; then
			cd $HOME/aliaz/ && ./aliaz.sh --name="$NAME" --command="$COMMAND" --home --clear
		elif [ "$mkHOME" = 'false' ] && [ "$CLEAR" = 'false' ]; then
			cd $HOME/aliaz/ && ./aliaz.sh --name="$NAME" --command="$COMMAND"
		fi
	fi
fi
